Кнопка "Дякую"
hurtom/toloka pull request #53
Opened 2017-06-28 19:28 UTC by chief-j

Уважно перевірив зміни у файлах

2017-06-30 07:13 UTC, konfuciusu reviewed
треба деякі зміни

2017-06-30 07:13 UTC, konfuciusu commented on install/sql/mysql.sql
> +  `thanked_count` int(11) NOT NULL DEFAULT 0 COMMENT 'Кількість "Дякую" на прикріпленні',
коментарі не потрібно,
стовпець бажано зробити однаковим, як в https://github.com/hurtom/toloka/blob/master/install/sql/toloka_old.sql:
<pre>`thanks` mediumint(8) NOT NULL DEFAULT '0',</pre>

2017-06-30 07:13 UTC, konfuciusu commented on install/sql/mysql.sql
> +  `thanked` text NOT NULL DEFAULT '{"data":[]}' COMMENT 'Хто подякував за вкладення'
замість `text` краще створити окрему таблицю, як в https://github.com/hurtom/toloka/blob/master/install/sql/toloka_old.sql

2017-06-30 07:13 UTC, konfuciusu commented on library/ajax/thanks.php
> +    $this->ajax_die($lang['FAILED']);
закоментований код треба забрати

2017-06-30 07:13 UTC, konfuciusu commented on library/ajax/thanks.php
> +?>
для чого `?><?php` тут?

2017-06-30 07:13 UTC, konfuciusu commented on library/ajax/thanks.php
> +		$json_list = json_decode($sql['thanked']);
це треба тоді переробити під окрему таблицю

2017-06-30 07:13 UTC, konfuciusu commented on library/ajax/thanks.php
> +		//{"data":[]}
треба забрати

2017-06-30 07:13 UTC, konfuciusu commented on styles/templates/default/viewtopic_attach.tpl
> +		<td><b>{L_RATING}:</b></td>
оцінки немає в коді, тому або додати її там, або забрати звідси

2017-06-30 19:34 UTC, chief-j commented on install/sql/mysql.sql
> +  `thanked` text NOT NULL DEFAULT '{"data":[]}' COMMENT 'Хто подякував за вкладення'
Я не знаходив у _old такої таблиці

2017-06-30 19:36 UTC, chief-j commented on install/sql/mysql.sql
> +  `thanked_count` int(11) NOT NULL DEFAULT 0 COMMENT 'Кількість "Дякую" на прикріпленні',
Коментарі сильно не заважать. Наступники легше зрозуміють, для чього ці рядки
Стовпець перейменую

2017-06-30 19:37 UTC, chief-j commented on library/ajax/thanks.php
> +?>
Я не перфекціоніст

2017-06-30 19:41 UTC, chief-j commented on styles/templates/default/viewtopic_attach.tpl
> +		<td><b>{L_RATING}:</b></td>
Добре. Заберу її звідни

2017-06-30 21:51 UTC, konfuciusu commented on install/sql/mysql.sql
> +  `thanked` text NOT NULL DEFAULT '{"data":[]}' COMMENT 'Хто подякував за вкладення'
таблиця називається bb_attachments_rating

2017-07-01 04:47 UTC, chief-j commented
Як відбувається запис тих користувачів, які подякували за прекріплення?

2017-07-01 10:04 UTC, konfuciusu commented
```
CREATE TABLE `bb_attachments_rating` (
  `attach_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `user_id` mediumint(9) NOT NULL DEFAULT '0',
  `thanked` tinyint(1) NOT NULL DEFAULT '0',
  `rating` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`attach_id`,`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

користувач 11 подякував за прикріплення 22:
attach_id = 22
user_id = 11
thanked = 1

2017-07-01 10:18 UTC, chief-j commented
Зрозумів. Зараз перепишу

2017-07-01 11:05 UTC, konfuciusu commented on library/ajax/thanks.php
> +		DB()->query("UPDATE " . BB_ATTACHMENTS_DESC . " SET thanks = $amount WHERE attach_id = $attach_id");
можна спростити до:

```
DB()->query("UPDATE " . BB_ATTACHMENTS_DESC . " SET thanks = thanks + 1 WHERE attach_id = $attach_id");
```

2017-07-01 11:05 UTC, konfuciusu commented on library/attach_mod/displaying_torrent.php
> +	foreach ($sql_rating as $row) {
змішані таби і пробіли

2017-07-01 11:05 UTC, konfuciusu commented on library/language/uk/main.php
> +$lang['THANKS'] = 'Дякую!';
треба додати в англійську мову, бо всі переклади генеруються звідти

2017-07-01 11:30 UTC, chief-j commented on library/ajax/thanks.php
> +		DB()->query("UPDATE " . BB_ATTACHMENTS_DESC . " SET thanks = $amount WHERE attach_id = $attach_id");
Логічно

2017-07-15 18:20 UTC, yukoff requested changes
Потрібно привести у відповідність до PSR-2

2017-07-15 18:20 UTC, yukoff commented on library/attach_mod/displaying_torrent.php
> +	foreach ($sql_rating as $row) {
Забудьте про таби - в [coding style](http://www.php-fig.org/psr/psr-2/) їх не зустрінеш:
> Code MUST use 4 spaces for indenting, not tabs.

В корні лежить файл [.editorconfig](https://github.com/hurtom/toloka/blob/master/.editorconfig) - я раджу додавати відповідний плагін до редактора, якщо не підтримується "з коробки".

P.S. Схоже прийшов час щось типу StyleCI підключати, хоча там батьківський код не факт, що пройде 😉

2017-08-14 18:28 UTC, konfuciusu commented
@yukoff тут потрібні ще зміни?

2017-08-14 23:43 UTC, yukoff requested changes
На додачу до коментарів по рев'ю треба прибрати з коміта файл `internal_data/cache/.htaccess`
```
git checkout master -- internal_data/cache/.htaccess
git add internal_data/cache/.htaccess
git commit --amend
```

2017-08-14 23:43 UTC, yukoff commented on library/language/en/main.php
> +//Інші мовні коди
Навіщо в англомовному файлі україномовні коментарі?

2017-08-14 23:43 UTC, yukoff commented on library/language/en/main.php
> +//Вкладення торрент
що це значить? + попередній коментар щодо англ. мови

2017-08-14 23:43 UTC, yukoff commented on library/includes/init_bb.php
> +define('BB_ATTACHMENTS_RATING', 'bb_attachments_rating');
Тут відсортовано за абеткою, тобто має бути після `BB_ATTACHMENTS_DESC`

2017-08-14 23:43 UTC, yukoff commented on install/sql/mysql.sql
> +  `thanks` mediumint(8) NOT NULL DEFAULT '0'
Воно може бути негативним? Більшість лічильників мають тип `BIGINT(20) UNSIGNED`, тож гадаю краще
```sql
`thanks` bigint(20) unsigned NOT NULL DEFAULT 0
```

2017-08-14 23:43 UTC, yukoff commented on library/attach_mod/displaying_torrent.php
> +        $can_thank = isset($row['thanked']) ? false : true;
Враховуючи, що типове значення `0`, краще так:
```php
$can_thank = isset($row['thanked']) && !!$row['thanked'] ? false : true;
```

2017-08-14 23:45 UTC, yukoff commented
@konfuciusu Так, відписав у рев'ю

2017-08-15 00:15 UTC, yukoff commented on install/sql/mysql.sql
> +  `user_id` mediumint(9) NOT NULL DEFAULT '0',
Для PK для `attach_id` та `user_id` нема потреби в `DEFAULT 0`

2017-08-15 00:15 UTC, yukoff commented on install/sql/mysql.sql
> +) ENGINE=MyISAM DEFAULT CHARSET=utf8;
В поточній схемі всі таблиці в InnoDB

2017-08-15 00:15 UTC, yukoff commented on install/sql/mysql.sql
> +  `rating` tinyint(1) NOT NULL DEFAULT '0',
Для цих двох `DEFAULT 0` (без лапок) - навіщо в `int` писати строку та змушувати сервер БД робити приведення типів на кожному `INSERT`-і...

2017-08-15 13:34 UTC, yukoff commented on install/sql/mysql.sql
> +  `thanks` mediumint(8) NOT NULL DEFAULT '0'
Я тут ще в ORM моделях звернув увагу - пропоную перейменувати у `thanks_count` - більш зрозуміле призначення та буде відповідати іменування інших полів

2017-08-18 19:26 UTC, yukoff commented
@konfuciusu, Я зробив необхідні зміни, але не можу їх додати до цього PR 😕

@chief-j, А чи стоїть прапорець ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) для цього PR? Бо не хотілося б плодити PR для кожної зміни...

2017-08-18 19:48 UTC, yukoff commented on library/ajax/thanks.php
> +?>
До речі, зовсім забув! На майбутнє - **не треба так робити** (тобто ставити закриваючий php-тег `?>`) в файлах, що не містять в собі html (а я сподіваюсь, що подібного ~~лайн~~ "спагетті" ніхто не плодить 😉) Тобто, майже ніколи.

Бо елементарний пробіл або симол нової строки в кінці буде відправлений клієнту. Якщо надсилати заголовки після включення такого файлу та без використання буферизації виводу то цей симол пробілу чи-то нової строки банально викличе застереження "headers already sent". Ось [стаття](https://www.sitepoint.com/should-you-close-your-php-code-tags/) на тему.

2017-08-18 20:06 UTC, yukoff commented on library/ajax/thanks.php
> +global $userdata;
До речі, маємо проблему - обидва коміти зробили з файлів "кашу" з символів переносу строки - CRLF (win) та LF (unix). На жаль, на ґітхабі цього не видно. Я вже писав про [.editorconfig](http://editorconfig.org/) - плагіни є для багатьох редакторів. Я в #73 в документацію теж додав.

2017-08-19 07:45 UTC, chief-j commented
@yukoff Тільки Конфуцій може додавати зміни у PR
Завтра внесу всі корисні і не зовсім побажання

2017-08-19 07:50 UTC, chief-j commented
> А чи стоїть прапорець "Allow edits from maintainers" для цього PR? Бо не хотілося б плодити PR для кожної зміни...

Раніше, цієї галочки не помічав. Спробуй зараз

2017-08-19 07:56 UTC, chief-j reviewed
Добре

2017-08-19 14:07 UTC, yukoff commented
@chief-j Дякую, все гаразд. Але краще зроблю rebase + squash, бо важкувато буде таке злиття продивитись.

2017-08-19 14:19 UTC, yukoff commented
@konfuciusu, з цим наче все, можна мержити.

P.S. В старій схемі на таблиці `bb_attachments_desc` окрім колонки `thanks_count` (що раніше була `thanks`) є ще оці:
```sql
  `rating_sum` int(11) NOT NULL DEFAULT '0',
  `rating_count` int(11) NOT NULL DEFAULT '0',
  `force_private` tinyint(1) NOT NULL DEFAULT '0',
```

Вони ж не стосуються цього PR?

2017-08-19 14:20 UTC, yukoff approved these changes

2017-08-19 14:39 UTC, chief-j commented
`  `rating_sum` int(11) NOT NULL DEFAULT '0',
  `rating_count` int(11) NOT NULL DEFAULT '0',`

Саме ці стосуються до оцінки релізу (зірочки)

2017-08-19 14:51 UTC, yukoff commented
@chief-j Та я власне по контексту зрозумів 😉 Просто наче окремої задачі ще не було, ось і вирішив уточнити.

2017-08-19 16:18 UTC, chief-j commented
Можеш створити таке завдання. Список треба наповнювати

2017-08-19 19:48 UTC, konfuciusu commented
Так, оцінки/зірки нехай будуть окремо.

2017-08-20 03:10 UTC, merged